language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t nsvergun/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true nsvergun/docker-react npm run test